name: Visualize repo
on:
  push:
    branches:
      - Feature/Add-Import-Visualization
jobs:
  update-diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bc-repo-projects/repo-visualizer@Feature/Add-Import-Visualization
        with:
          output_file: diagram.svg
          excluded_paths: node_modules,dist
